# Usage
#
# Settings.default_host
#
common:
  http_basic_username: things
  http_basic_password: welike
  default_host: plist.tv
  faye_token: likesomethinggood
  faye_url: http://localhost:9292/faye

development:
  default_host: localhost:3000

test:
  default_host: plist.dev

staging:
  default_host: dev.plist.tv

production:
