package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: on
javascript_compressor: on
javascript_compressor: uglifier

javascripts:
  vendor:
    - public/javascripts/vendor/jquery.min.js
    - public/javascripts/vendor/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/vendor/underscore-min.js
    - public/javascripts/vendor/backbone-min.js
    - public/javascripts/vendor/haml.js
    - public/javascripts/vendor/swfobject.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/vendor/modernizr.js

  plugins:
    - public/javascripts/plugins/jquery-fallr-1.2.min.js
    - public/javascripts/plugins/jquery.clickmenu.js
    - public/javascripts/plugins/jquery.ctNotify.js
    - public/javascripts/plugins/jquery.autocomplete-min.js
    - public/javascripts/plugins/jquery.jQTubeUtil.min.js
    - public/javascripts/plugins/json.js
    - public/javascripts/plugins/placeholder.js

  modals:
    - public/javascripts/modals/*.js

  app:
    - public/javascripts/functions.js
    - public/javascripts/playlist.js
    - public/javascripts/player.js
    - public/javascripts/youtube.js
    - public/javascripts/application.js

stylesheets:
  app:
    - public/stylesheets/application.css
    - public/stylesheets/plugins.css
